{% set name = "pgzero" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pgzero-{{ version }}.tar.gz
  sha256: 8cadc020f028cbac3e0cbd3bb9311a1c045f1deedac7917ff433f986c38e6106

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 1
  noarch: python
  entry_points:
    - pgzrun = pgzero.runner:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pygame >=2.0,<3.dev0
    - numpy

test:
  imports:
    - pgzero
    - pgzrun  # [not osx]
  commands:
    - pip check
    - pgzrun --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pypi.python.org/pypi/pgzero
  summary: A zero-boilerplate 2D games framework
  license: LGPL-3.0-only
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - jamesmyatt
